### ISSUE TITLE
Review Error View

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#280]
- [x]  clean up error view #239 
- [x] handle vimeo request errors #273 
- [x] scroll bar in error view #278 
- [x] handle permissions blocking embeds for youtube #276 
- [x]  handle case where yt embed api lib is not loaded when not connected to internet #258

**Comment by pdehaan** [comment]
- [ ] VEVO videos on YouTube are not able to be played in Min Vid #285

**Comment by meandavejustice** [comment]
god vevo is the worst

**Comment by meandavejustice** [comment]
fixed in #292
